### ISSUE TITLE
Settle on the date of our first E-meeting

### ISSUE THREAD

**Issue by CamilBouzidi** [laurentlaurent/ShutterFeed-a-soen-341-repo#1]
Hello Team!

We need to find a time for our first meeting, preferably a couple of days prior to the tutorial so that we have something to show for it.

Please check out the doodle below:

https://doodle.com/poll/drxx7k8ctcuwv6rz

**Comment by CamilBouzidi** [comment]
Hello all,

First meeting is today at 4 PM.

**Comment by laurent-lao** [comment]
Meeting ajourned
