### ISSUE TITLE
Task 4.5 Pass Acceptance Tests 

### ISSUE THREAD

**Issue by jmezaber** [laurentlaurent/ShutterFeed-a-soen-341-repo#100]
| Task| P |
|:-----------------------:|:---:|
|Pass Acceptance Tests| Medium|

There are a few acceptance tests that have been set for our user story on [Follow other](#15). They must all pass with any submit. They are the following **(please reference a commit if you check an item off of the list):** 

This task's priority point is medium because even though it is not in the developing process yet, it will because important to pass the acceptance tests.

------------------------------------------

## Acceptance Tests
- [x] Can post a picture
- [x] Picture will disappear after 24h

**Comment by laurent-lao** [comment]
Will Close #59 when delivered

**Comment by CamilBouzidi** [comment]
Closed with #129
