### ISSUE TITLE
Add Webpack to the project

### ISSUE THREAD

**Issue by tjosepo** [laurentlaurent/ShutterFeed-a-soen-341-repo#11]
Adding Webpack to the project would highly increase our productivity when working on front-end features.

Webpack is a javascript module bundler. Its main purpose is to **run script and compile .js, .css, and image files into smaller, more concise files**.

Webpack would also allow us to **run static analysis tools** such as ESLint.

Having Webpack already set up would also allow us to **quickly add a framework like React or Angular** if we ever decide to use them.

**Comment by laurent-lao** [comment]
Great idea!

**Comment by CamilBouzidi** [comment]
Hello,

I agree with using Webpack! There is also an extension for managing it within VS Code, which I think could be beneficial to our workflow

**Comment by laurent-lao** [comment]
Also works with Rider! See [Using Webpack](https://www.jetbrains.com/help/rider/Using_Webpack.html)

**Comment by laurent-lao** [comment]
@tommy-josepovic Do you think web pack is still valid? If not, we can close this issue.

**Comment by tjosepo** [comment]
Indeed. This issue is obsolete.
