### ISSUE TITLE
 Grading Scheme for Sprint 4

### ISSUE THREAD

**Issue by jmezaber** [laurentlaurent/ShutterFeed-a-soen-341-repo#120]
------------------------------------------

## Grading Scheme for Sprint 4
**GENERAL**
- [x] **Done Enough Work?**: (0.5) Finished all the core features and additional features & they all work well in your environment

**PLANNING**
- [x] **Enforcement of planning**: see attributes of planning from prior sprint
- [x] **Story description, Points, Risk, Priority**: (-0.1 for each missing part) Document the issues about the additional feature with risk & priority & story points for user stories (label them or write sth inside the issue).
- [x] **Frequent meetings (scrum) with meeting minutes available**

**CODE**
- [x] **Directory and package structure**: (0.5) Files with similar functionality are organized in packages
- [ ] **Quality of Code**: (0.5) Looks good (no clear error or inefficiency in the code)
- [ ] **Coding style enforced**: (0.5) 0.5: The coding style is enforced (e.g., follow the naming and coding convention that your team defined/reused) 
    * You need to explicitly mention the coding style and naming convention that you follow. Mention them in your GitHub page. You can reuse existing conventions or you can create your own. However, you need to follow the same style throughout your project.

**REPO**
- [x] **1.Commit logs descriptive**: (- 0.1 for each unfinished case)
- [x] **2.Commits referenced with issues**: (- 0.1 for each unfinished case)
- [x] **3.Discussion on GitHub Items**: (- 0.1 for each unfinished case)
- [x] **4.Review on GitHub items**: (- 0.1 for each unfinished case)

**TESTING/VALIDATION**
- [ ] **Continuous integration  with testing executed for every commit**: (-0.5 if not setup/working)
- [ ] **Acceptance testing for every user story**: (-0.5 if not setup/working)
- [ ] **Quality of test code**: (0.5) Test cases are testing different input groups 
    * You need to create at least 10 test cases in total for different classes (or equivalents)

**MICS**
- [x] Show up in tutorials meeting with TA
------------------------------------------

**Comment by CamilBouzidi** [comment]
Closed with #130
