### ISSUE TITLE
Completing Starting User Stories

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#3]
Using assignment guidelines, produce basic user stories

* Add User Stories here: https://github.com/CamilBouzidi/-REDACTED-a-SOEN-341-Repo/wiki/User-Stories
* And create an Issue for that user story

## Create User stories for these features
- [x] Post pictures: as a user I want my life with my friends in the form of pictures that I would upload
- [x] Leave comments on a posted picture: As a user I want to be able to comment a picture to let others know how I feel about the picture.
- [x] Follow user (notification for every post): As a user, I want to see pictures from my friends on a reoccurring basis.
## Maybe
- [x] Have IG-type stories: As a user, I would prefer to have the ability to post pictures that disappear after a certain period of time to preserve the aesthetics and themes of my account while also informing my friends.

**Comment by iamL2** [comment]
@laurentlaurent Testing push notif

**Comment by iamL2** [comment]
@laurentlaurent Testing push notif

**Comment by iamL2** [comment]
@laurentlaurent Retest push notif

**Comment by jmezaber** [comment]
Sorry people, I clicked the wrong button

**Comment by tjosepo** [comment]
Seems like all major stories have been written. I'm declaring this issue as closed.
