### ISSUE TITLE
Sprint 2: First meeting

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#32]
Feel free to add things to discuss:
- [x] Progress with Angular/React tutorial
- [x] Choose Framework
- [x] Choose Dev Environment
- [x] ASP.net Core difference
- [x] Structure of Architecture, Interface, Class designs (tools to use...)
- [x] Re-use existing code to accelerate dev
- [x] Remind: Validation tests for User Stories 1 to 3
- [x] Remind: Break down User Stories tasks

**Comment by laurent-lao** [comment]
Need to decide on meeting time/date

**Comment by CamilBouzidi** [comment]
https://doodle.com/poll/zqnt6rbr69cayywz

I only made one for the next 2 days since I personally won't be available at all on Thursday.

**Comment by laurent-lao** [comment]
Meeting set for Wed 10pm
