### ISSUE TITLE
Draw.io Setup

### ISSUE THREAD

**Issue by jmezaber** [laurentlaurent/ShutterFeed-a-soen-341-repo#36]
|Task|SP|
|:----|:-----|
|Draw.io Setup| 1|

We can use draw.io to create the UMLs we need.

**Comment by jmezaber** [comment]
So [this](https://drive.google.com/file/d/1I0mw6MCx_GZGa_2wRWuQphPxF7OyLbbj/view?usp=sharing) is what we can use to draw any UML we need. Btw, it is blank right now

**Comment by laurent-lao** [comment]
Looks good. Could you add it in the wiki? (and make a pull request to resolve it automatically)
