### ISSUE TITLE
Create Periodic Progress Reports (Stand-ups) in wiki

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#56]
To ensure that we meet the grading scheme of having periodic meetings, a Stand-ups page with project progress shall be created.

**Comment by CamilBouzidi** [comment]
Isn't this redundant compared to meeting minutes and the project board? Both fulfil the purpose of those progress reports, from what I can gather.

**Comment by laurent-lao** [comment]
@CamilBouzidi I hear you, but meetings minutes are for meetings only. In an agile environment, we're supposed to have even more frequent meetings (daily stand-ups). The board `done` gets archived every sprint, so having a progress report (think about it like a patch notes) is a good alternative I believe.
