### ISSUE TITLE
Create Documentation for Picture Upload

### ISSUE THREAD

**Issue by laurent-lao** [laurentlaurent/ShutterFeed-a-soen-341-repo#69]
Priority: Medium. Point: 1.

Provide some documentation in /docs on how to use the components related to Picture Upload to facilitate creating components that hook into it and stuff. Linking the guide used (if any) can be enough.

- [ ] Doc for Picture Upload components/services in `/docs/Project-Documentation.md` and `/docs`

**Comment by CamilBouzidi** [comment]
It was fixed and redirected in with PR #125 .
