### ISSUE TITLE
Changing the Name

### ISSUE THREAD

**Issue by CamilBouzidi** [laurentlaurent/ShutterFeed-a-soen-341-repo#7]
Hey all,

Do we have any ideas for the names that we could use for our project? Here are some of my suggestions:
- LifeAlbum
- SeeMyPics
- PhotoFeed

**Comment by tjosepo** [comment]
I agree with PhotoFeed

Good one.

**Comment by laurent-lao** [comment]
I like them all.

I'd like to suggest ShutterFeed (since PhotoFeed is an actual program)
