### ISSUE TITLE
Task 2.2: Find a way to make the UI scalable

### ISSUE THREAD

**Issue by jmezaber** [laurentlaurent/ShutterFeed-a-soen-341-repo#75]
| Task | P |
|:-----------------------|:-:|
| 2.2: Find a way to make the UI scalable| Medium|

Using Angular Material for UI, the comment UI should be made scalable.

The priority point is medium because it is not a requirement to make the comment UI scalable, it is just to make the web page nicer.

## Related features/user stories

* Related to [User Story 2](#13)

**Comment by CamilBouzidi** [comment]
Angular is really good at doing this, so it shouldn't be where we should direct most of our work.
