### ISSUE TITLE
Task 2.3: Have comment show up under picture

### ISSUE THREAD

**Issue by jmezaber** [laurentlaurent/ShutterFeed-a-soen-341-repo#76]
| Task | P |
|:-----------------------|:-:|
| 2.3: Have comment show up under picture| High |

The task has high priority because this is the main feature of [User Story 2](#13). When a user posts a comment, that comment should appear under the picture. For this to happen, Fireabase's database has to be connected to the front end.

## Related features/user stories

* Related to [User Story 2](#13)

**Comment by CamilBouzidi** [comment]
Since this is the core of [User Story 2](#13), it could maybe have a priority even higher than 8.
