### ISSUE TITLE
Task 4.1: Create a story type

### ISSUE THREAD

**Issue by jmezaber** [laurentlaurent/ShutterFeed-a-soen-341-repo#95]
| Task| P |
|:-----------------------:|:---:|
|Create a story type  | High|

Some sort of "story" type is needed for this feature. This would imply that pictures posted in our stories are stored differently than the way pictures from the feed are stored.

The priority point of this task is high because it is a crucial part of the development part of this feature.

## Related features/user stories

* Related to [User Story 4](#24)

**Comment by CamilBouzidi** [comment]
This was done in the Stories-All branch.
