### ISSUE TITLE
Task 4.2: Post a picture to the story

### ISSUE THREAD

**Issue by jmezaber** [laurentlaurent/ShutterFeed-a-soen-341-repo#97]
| Task| P |
|:-----------------------:|:---:|
|Post a picture to the story  | High|

The user is able to post a picture to the "story".

The priority point of this task is high because it is a main part of this feature.

## Related features/user stories

* Related to [User Story 4](#24)

**Comment by CamilBouzidi** [comment]
Finished with Stories-All branch
