### ISSUE TITLE
Task 4.3: Make the picture disappear after 24h

### ISSUE THREAD

**Issue by jmezaber** [laurentlaurent/ShutterFeed-a-soen-341-repo#98]
| Task| P |
|:-----------------------:|:---:|
|Make the picture disappear after 24h  | Medium|

The picture posted by the user on the "story" will disappear after 24h.

The priority point of this task is medium because it is not crucial however it is implied in the feature.

## Related features/user stories

* Related to [User Story 4](#24)

**Comment by CamilBouzidi** [comment]
This was done in Stories-All branch
