### ISSUE TITLE
Task 4.4: Set Acceptance tests

### ISSUE THREAD

**Issue by jmezaber** [laurentlaurent/ShutterFeed-a-soen-341-repo#99]
| Task| P |
|:-----------------------:|:---:|
|Set Acceptance Tests| Medium|

There are a few acceptance tests that have been set for our user story on [ShutterFeed Stories](#24). They are the following: 

Setting acceptance tests for this user story is a medium priority right now since this user story is not being developped soon.

------------------------------------------

## Acceptance Tests

| Input| Expected Output |
|:-----------------------:|:---:|
| Posts a picture | Picture appears in the Story and disappears after 24h|

**Comment by CamilBouzidi** [comment]
This has been achieved in the stories-all branch.
